#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

STACK_NAME="${STACK_NAME:-uno-multiplayer}"
REGION="${AWS_REGION:-us-east-1}"
ENV="${ENVIRONMENT:-prod}"

info()    { echo "[INFO]  $*"; }
success() { echo "[OK]    $*"; }
err()     { echo "[ERROR] $*" >&2; exit 1; }
step()    { echo ""; echo ">>> $*"; }

echo ""
echo "================================================"
echo "  UNO Multiplayer - Deploy"
echo "  Stack : $STACK_NAME  Region: $REGION  Env: $ENV"
echo "================================================"

step "Checking prerequisites..."

find_tool() {
  local name="$1"; shift
  if command -v "$name" >/dev/null 2>&1; then command -v "$name"; return; fi
  for p in "$@"; do [ -f "$p" ] && echo "$p" && return; done
  echo ""
}

AWS_CMD=$(find_tool aws "/c/Program Files/Amazon/AWSCLIV2/aws.exe" "/c/Program Files (x86)/Amazon/AWSCLIV2/aws.exe")
SAM_CMD=$(find_tool sam "/c/Program Files/Amazon/AWSSAMCLI/bin/sam.cmd" "/c/Program Files (x86)/Amazon/AWSSAMCLI/bin/sam.cmd")
NODE_CMD=$(find_tool node "/c/Program Files/nodejs/node.exe")
NPM_CMD=$(find_tool npm "/c/Program Files/nodejs/npm.cmd")

[ -z "$AWS_CMD" ]  && err "AWS CLI not found."
[ -z "$SAM_CMD" ]  && err "SAM CLI not found."
[ -z "$NODE_CMD" ] && err "Node.js not found."
[ -z "$NPM_CMD" ]  && err "npm not found."

info "aws  -> $AWS_CMD"
info "sam  -> $SAM_CMD"

AWS_ACCOUNT=$("$AWS_CMD" sts get-caller-identity --query Account --output text 2>/dev/null) \
  || err "AWS credentials not configured. Run: aws configure"
success "Prerequisites OK  (AWS Account: $AWS_ACCOUNT)"

SAM_BUCKET="${STACK_NAME}-sam-${AWS_ACCOUNT}-${REGION}"

step "Setting up SAM artifacts bucket: $SAM_BUCKET"
if "$AWS_CMD" s3 ls "s3://$SAM_BUCKET" >/dev/null 2>&1; then
  success "Bucket already exists"
else
  "$AWS_CMD" s3 mb "s3://$SAM_BUCKET" --region "$REGION"
  success "Bucket created"
fi

step "Installing backend dependencies..."
for dir in "backend/create-game" "backend/join-game" "backend/make-move" "backend/draw-card" "backend/get-game-state" "backend/websocket-handler" "backend/start-game" "backend/restart-game"; do
  full="$ROOT_DIR/$dir"
  [ -d "$full" ] || err "Directory not found: $full"
  info "  $dir"
  (cd "$full" && "$NPM_CMD" install --production --silent)
done
success "Dependencies installed"

step "Building SAM application..."
(cd "$ROOT_DIR/infrastructure" && "$SAM_CMD" build --parallel)
success "SAM build complete"

step "Deploying SAM stack (this may take a few minutes)..."
(cd "$ROOT_DIR/infrastructure" && "$SAM_CMD" deploy \
  --stack-name "$STACK_NAME" \
  --s3-bucket "$SAM_BUCKET" \
  --region "$REGION" \
  --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
  --parameter-overrides "Environment=$ENV" \
  --no-fail-on-empty-changeset)
success "SAM deploy complete"

step "Fetching stack outputs..."

get_output() {
  "$AWS_CMD" cloudformation describe-stacks \
    --stack-name "$STACK_NAME" --region "$REGION" \
    --query "Stacks[0].Outputs[?OutputKey=='$1'].OutputValue" --output text
}

REST_API_URL=$(get_output "RestApiUrl")
WEBSOCKET_URL=$(get_output "WebSocketUrl")
CLOUDFRONT_URL=$(get_output "CloudFrontUrl")
FRONTEND_BUCKET=$(get_output "FrontendBucketName")

[ -z "$REST_API_URL" ]    && err "Could not read RestApiUrl"
[ -z "$WEBSOCKET_URL" ]   && err "Could not read WebSocketUrl"
[ -z "$CLOUDFRONT_URL" ]  && err "Could not read CloudFrontUrl"
[ -z "$FRONTEND_BUCKET" ] && err "Could not read FrontendBucketName"

info "REST API   : $REST_API_URL"
info "WebSocket  : $WEBSOCKET_URL"
info "CloudFront : $CLOUDFRONT_URL"
info "S3 Bucket  : $FRONTEND_BUCKET"

step "Writing frontend config..."
CONFIG="// Auto-generated by deploy.sh on $(date -u '+%Y-%m-%d %H:%M UTC')
const API_CONFIG = {
  REST_API_URL: '${REST_API_URL}',
  WEBSOCKET_URL: '${WEBSOCKET_URL}',
  FRONTEND_URL: '${CLOUDFRONT_URL}',
  REGION: '${REGION}',
  ENV: '${ENV}'
};
if (typeof module !== 'undefined') module.exports = API_CONFIG;
"
printf '%s' "$CONFIG" > "$ROOT_DIR/config/api-config.js"
printf '%s' "$CONFIG" > "$ROOT_DIR/frontend/config/api-config.js"
success "Config written"

step "Uploading frontend to S3..."
# All files get no-cache so every deploy is immediately visible to all users
"$AWS_CMD" s3 sync "$ROOT_DIR/frontend/" "s3://$FRONTEND_BUCKET/" \
  --region "$REGION" \
  --delete \
  --cache-control "no-cache, no-store, must-revalidate" \
  --exclude "*.DS_Store"
success "Frontend uploaded"

step "Invalidating CloudFront cache..."
CF_DOMAIN="${CLOUDFRONT_URL#https://}"
CF_DIST_ID=$("$AWS_CMD" cloudfront list-distributions \
  --query "DistributionList.Items[?DomainName=='${CF_DOMAIN}'].Id" \
  --output text 2>/dev/null || true)

if [ -n "$CF_DIST_ID" ] && [ "$CF_DIST_ID" != "None" ]; then
  "$AWS_CMD" cloudfront create-invalidation \
    --distribution-id "$CF_DIST_ID" --paths "/*" --output text >/dev/null
  success "Cache invalidated (distribution: $CF_DIST_ID)"
else
  info "Distribution ID not found - skipping invalidation"
fi

echo ""
echo "================================================"
echo "  Deployment Complete!"
echo "  Game URL: $CLOUDFRONT_URL"
echo "================================================"
echo ""